[workspace]
authors = ["K. Arthur Endsley <endsley@umich.edu>"]
channels = ["conda-forge"]
name = "demo-M5-project"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.12,<3.13"
numpy = "<2"
earthaccess = ">=0.15.1,<0.16"
h5py = ">=3.15.1,<4"
matplotlib = ">=3.10.8,<4"
pyproj = ">=3.7.2,<4"
rasterio = ">=1.4.4,<2"
rioxarray = ">=0.20.0,<0.21"
xarray = ">=2025.12.0,<2026"
papermill = ">=2.6.0,<3"
notebook = ">=7.5.1,<8"
ipykernel = ">=7.1.0,<8"

[pypi-dependencies]
py4eos = ">=0.5.0, <0.6"
snakemake = ">=9.14.4, <10"
